### ISSUE TITLE
Add videoscales before the sinkpads of videomixer.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pitivi/gst-editing-services#43]
One should look at how video-transitions work.

**Comment by vliaskov** [comment]
perhaps this is useful and relevant, a small patch to generate audio/video files with different dimensions, so that we can test videoscaling for videomixer and transitions:
https://github.com/vliaskov/PitiviGes/commit/7367bf3db2dc38b0f46a6fa9c0ca95e19b7d7b44

As for adding videoscale to the mixer, I haven't spent much time on this, but here's a work-in-progress patch (completely untested unfortunately):
https://github.com/vliaskov/PitiviGes/commit/b4ac0a070cdd87544d21fcead0b11a316d373999

**Comment by thiblahute** [comment]
Obselte
